### ISSUE TITLE
Support SELECT?

### ISSUE THREAD

**Issue by ramSeraph** [fastio/1store#39]
Any plans on supporting "SELECT" call and the whole concept of database from redis?

Was trying to test pedis against the redis test suite.. thats where it came up

Feels like it would be easy to implement.. I mean we can just add the database number as suffix to the keyspace names.. 

I don't mind getting this done.. if there is no objection to this.

**Comment by fastio** [comment]
@ramSeraph  You are right. It's easy to implement the SELECT command for pedis. I have finished it.
c0d6a8c89063bd0b7c75ff808ea57721f537bc79

I'll try to test pedis against the redis test suite later. Thanks for your advice.

**Comment by ramSeraph** [comment]
Damn.. that was fast.. 
Wasn't much of an advice, more like a request for validation, so that i could get my hands dirty with the code and seastar in general.  

Anyway, will drop instructions here on how i ran the redis test suite.. its quirky and in tcl and i have just about barely managed to figure it out..

**Comment by ramSeraph** [comment]
I don't even remember where I have the test suite thing anymore. This was long pending to be closed. Thanks
